=== dgilman/burn/burn/Binaries/Sources/vcdimager-0.7.23/frontends/xml/videocd.dtd
<!--
 VCDImager VideoCD XML 1.0 DTD 

 Copyright (c) 2000-2001  Herbert Valerio Riedel <hvr@gnu.org>

 Namespace = "http://www.gnu.org/software/vcdimager/1.0/"

 This DTD module is identified by the PUBLIC and SYSTEM identifiers:

 PUBLIC "-//GNU//DTD VideoCD//EN"
 SYSTEM "http://www.gnu.org/software/vcdimager/videocd.dtd"

 $Revision: 1.19 $
 $Date: 2001/08/29 13:21:50 $

-->

<!ENTITY % URI "CDATA">

<!ENTITY % itemattrs
 "id        ID           #REQUIRED
  src       %URI;        #REQUIRED"
>

<!ELEMENT videocd (option*,info,pvd,filesystem?,segment-items?,sequence-items,pbc?)>
<!ATTLIST videocd
  class     CDATA                    #REQUIRED
  version   CDATA                    #REQUIRED
  xmlns     %URI;                    #FIXED 'http://www.gnu.org/software/vcdimager/1.0/'
>

<!ELEMENT option EMPTY>
<!ATTLIST option 
  name	    CDATA	             #REQUIRED
  value     CDATA                    #IMPLIED
>

<!--======================================================================-->

<!ELEMENT info (album-id?,volume-count?,volume-number?,next-volume-use-sequence2?,next-volume-use-lid2?,restriction?,start-time-offset*)>

<!ELEMENT album-id (#PCDATA)>
<!ELEMENT volume-count (#PCDATA)>
<!ELEMENT volume-number (#PCDATA)>
<!ELEMENT next-volume-use-sequence2 EMPTY>
<!ELEMENT next-volume-use-lid2 EMPTY>
<!ELEMENT restriction (#PCDATA)>
<!ELEMENT start-time-offset (#PCDATA)>

<!--======================================================================-->

<!ELEMENT pvd (volume-id?,system-id?,application-id?,preparer-id?,publisher-id?)>

<!ELEMENT volume-id (#PCDATA)>
<!ELEMENT system-id (#PCDATA)>
<!ELEMENT application-id (#PCDATA)>
<!ELEMENT preparer-id (#PCDATA)>
<!ELEMENT publisher-id (#PCDATA)>

<!--======================================================================-->

<!ELEMENT filesystem (folder*,file*)>

<!ELEMENT folder (name,folder*,file*)>

<!ELEMENT file (name)>
<!ATTLIST file 
  src       %URI;          #REQUIRED
  format    (form1|mixed)  "form1"
>
<!ELEMENT name (#PCDATA)>

<!--======================================================================-->

<!ELEMENT segment-items (segment-item)+>
<!ELEMENT segment-item  (auto-pause)*>
<!ATTLIST segment-item 
  %itemattrs;
>

<!--======================================================================-->

<!ELEMENT sequence-items (sequence-item)+>

<!ELEMENT sequence-item (default-entry?,entry*,auto-pause*)>
<!ATTLIST sequence-item
  src       %URI;        #REQUIRED
  id        ID           #IMPLIED
>

<!ELEMENT default-entry EMPTY>
<!ATTLIST default-entry
  id        ID           #REQUIRED
>

<!ELEMENT entry (#PCDATA)>
<!ATTLIST entry
  id        ID           #IMPLIED
>

<!ELEMENT auto-pause (#PCDATA)>

<!--======================================================================-->

<!ELEMENT pbc (selection|playlist|endlist)+>

<!ENTITY % pbcattrs
" id        ID           #REQUIRED
  rejected  (true|false) 'false'"
>

<!ENTITY % XY "CDATA">

<!ENTITY % ofsattrs
 " ref       IDREF       #IMPLIED
   x1        %XY;        #IMPLIED
   y1        %XY;        #IMPLIED
   x2        %XY;        #IMPLIED
   y2        %XY;        #IMPLIED"
>

<!ELEMENT selection (bsn?,prev?,next?,return?,(multi-default|default)?,timeout?,wait?,loop?,play-item?,select*)>
<!ATTLIST selection
  %pbcattrs;
>

<!ELEMENT playlist (prev?,next?,return?,playtime?,wait?,autowait?,play-item+)>
<!ATTLIST playlist
  %pbcattrs;
>

<!ELEMENT endlist (next-volume?,play-item?)>
<!ATTLIST endlist
  %pbcattrs;
>

<!ELEMENT wait (#PCDATA)>
<!ELEMENT autowait (#PCDATA)>
<!ELEMENT playtime (#PCDATA)>
<!ELEMENT loop (#PCDATA)>

<!ELEMENT bsn (#PCDATA)>
<!ELEMENT prev EMPTY>
<!ELEMENT next EMPTY>
<!ELEMENT return EMPTY>
<!ELEMENT multi-default EMPTY>
<!ELEMENT default EMPTY>
<!ELEMENT timeout EMPTY>
<!ELEMENT play-item EMPTY>
<!ELEMENT select EMPTY>

<!ELEMENT next-volume (#PCDATA)>

<!ATTLIST multi-default
  numeric      (enabled|disabled)    'enabled'
>

<!ATTLIST loop
  jump-timing  (immediate|delayed)   'immediate'
>

<!ATTLIST prev 
  %ofsattrs;
>

<!ATTLIST next
  %ofsattrs;
>

<!ATTLIST return 
  %ofsattrs;
>

<!ATTLIST default
  %ofsattrs;
>

<!ATTLIST timeout
  ref       IDREF       #IMPLIED
>

<!ATTLIST play-item
  ref       IDREF       #IMPLIED
>

<!ATTLIST select
  %ofsattrs;
>

=== dgilman/burn/burn/Binaries/Sources/vcdimager-0.7.23/test/check_cue.xml
<?xml version="1.0"?>
<!DOCTYPE videocd PUBLIC "-//GNU//DTD VideoCD//EN" "http://www.gnu.org/software/vcdimager/videocd.dtd">
<!-- command arguments used: -=no-command-comment -=input videocd.cue -=output-file svcd1_cue.xml -->
<videocd xmlns="http://www.gnu.org/software/vcdimager/1.0/" class="vcd" version="2.0">
  <info>
    <album-id>CHECK</album-id>
    <volume-count>1</volume-count>
    <volume-number>1</volume-number>
    <restriction>1</restriction>
  </info>
  <pvd>
    <volume-id>SVCDTEST</volume-id>
    <system-id>CD-RTOS CD-BRIDGE</system-id>
    <application-id>VIDEOCD.APP;1</application-id>
    <preparer-id>GNU VCDIMAGER CHECK MODE</preparer-id>
    <publisher-id>PUBL_ID</publisher-id>
  </pvd>
  <segment-items>
    <segment-item src="item0001.mpg" id="segment-0000"/>
  </segment-items>
  <sequence-items>
    <sequence-item src="avseq01.mpg" id="sequence-00">
      <default-entry id="entry-000"/>
    </sequence-item>
  </sequence-items>
  <pbc>
    <selection id="selection-01">
      <bsn>1</bsn>
      <next ref="end-1" x1="0" y1="0" x2="0" y2="0"/>
      <return ref="end-1" x1="10" y1="20" x2="30" y2="40"/>
      <wait>-1</wait>
      <loop jump-timing="immediate">1</loop>
      <play-item ref="segment-0000"/>
      <select ref="playlist-01" x1="0" y1="0" x2="0" y2="0"/>
      <select ref="playlist-02" x1="0" y1="0" x2="0" y2="0"/>
      <select ref="end-1" x1="0" y1="0" x2="0" y2="0"/>
    </selection>
    <playlist id="playlist-01">
      <next ref="playlist-02"/>
      <return ref="end-1"/>
      <wait>5</wait>
      <autowait>0</autowait>
      <play-item ref="sequence-00"/>
      <play-item ref="entry-000"/>
    </playlist>
    <playlist id="playlist-02">
      <next ref="end-1"/>
      <return ref="end-1"/>
      <wait>5</wait>
      <autowait>0</autowait>
      <play-item ref="sequence-00"/>
    </playlist>
    <endlist id="end-1"/>
  </pbc>
</videocd>

=== dgilman/burn/burn/Binaries/Sources/vcdimager-0.7.23/test/check_nrg.xml
<?xml version="1.0"?>
<!DOCTYPE videocd PUBLIC "-//GNU//DTD VideoCD//EN" "http://www.gnu.org/software/vcdimager/videocd.dtd">

<!-- used by check_nrg.sh script -->

<videocd xmlns="http://www.gnu.org/software/vcdimager/1.0/" class="svcd" version="1.0">
  <info>
    <album-id>CHECK</album-id>
    <volume-count>1</volume-count>
    <volume-number>4</volume-number>
    <restriction>1</restriction>
  </info>
  <pvd>
    <volume-id>SVIDEOCD</volume-id>
    <system-id>CD-RTOS CD-BRIDGE</system-id>
    <application-id>SVIDEOCD.APP;1</application-id>
    <preparer-id>PREP_ID</preparer-id>
    <publisher-id>PUBL_ID</publisher-id>
  </pvd>

  <segment-items>
    <segment-item src="item0000.m1p" id="segment-0000"/>
    <segment-item src="item0000.m1p" id="segment-0001"/>
    <segment-item src="item0000.m1p" id="segment-0002"/>
  </segment-items>

  <sequence-items>
    <sequence-item src="avseq00.m1p" id="sequence-00"/>
    <sequence-item src="avseq00.m1p" id="sequence-01"/>
    <sequence-item src="avseq00.m1p" id="sequence-02"/>
    <sequence-item src="avseq00.m1p" id="sequence-03"/>
  </sequence-items>

  <pbc>
    <selection id="menu">
      <bsn>1</bsn>
      <next ref="lid-end"/>
      <return ref="lid-end"/>
      <wait>5</wait>
      <loop jump-timing="immediate">1</loop>
      <play-item ref="segment-0000"/>
      <select ref="lid-000" />
      <select ref="lid-001" />
      <select ref="lid-end" />
    </selection>

    <playlist id="lid-000">
      <next ref="lid-001"/>
      <return ref="lid-end"/>
      <wait>5</wait>
      <autowait>0</autowait>
      <play-item ref="sequence-00"/>
      <play-item ref="sequence-01"/>
      <play-item ref="segment-0001"/>
    </playlist>

    <playlist id="lid-001">
      <next ref="lid-end"/>
      <return ref="lid-end"/>
      <wait>5</wait>
      <autowait>0</autowait>
      <play-item ref="sequence-02"/>
      <play-item ref="sequence-03"/>
      <play-item ref="segment-0002"/>
    </playlist>

    <endlist id="lid-end" rejected="true"/>
  </pbc>
</videocd>

=== dgilman/burn/burn/Binaries/Sources/vcdimager-0.7.23/test/check_vcd11.xml
<?xml version="1.0"?>
<!DOCTYPE videocd PUBLIC "-//GNU//DTD VideoCD//EN" "http://www.gnu.org/software/vcdimager/videocd.dtd">

<!-- used by check_vcd11.sh script -->

<videocd xmlns="http://www.gnu.org/software/vcdimager/1.0/" class="vcd" version="1.1">
  <info>
    <album-id>CHECK</album-id>
    <volume-count>1</volume-count>
    <volume-number>4</volume-number>
    <restriction>1</restriction>
  </info>
  <pvd>
    <volume-id>VIDEOCD</volume-id>
    <system-id>CD-RTOS CD-BRIDGE</system-id>
    <application-id>VIDEOCD.APP;1</application-id>
    <preparer-id>PREP_ID</preparer-id>
    <publisher-id>PUBL_ID</publisher-id>
  </pvd>

  <sequence-items>
    <sequence-item src="avseq00.m1p" id="sequence-00"/>
    <sequence-item src="avseq00.m1p" id="sequence-01"/>
    <sequence-item src="avseq00.m1p" id="sequence-02"/>
    <sequence-item src="avseq00.m1p" id="sequence-03"/>
  </sequence-items>

</videocd>

=== dgilman/burn/burn/Binaries/Sources/vcdimager-0.7.23/test/check_vcd20.xml
<?xml version="1.0"?>
<!DOCTYPE videocd PUBLIC "-//GNU//DTD VideoCD//EN" "http://www.gnu.org/software/vcdimager/videocd.dtd">

<!-- used by check_vcd20.sh script -->

<videocd xmlns="http://www.gnu.org/software/vcdimager/1.0/" class="vcd" version="2.0">
  <info>
    <album-id>CHECK</album-id>
    <volume-count>1</volume-count>
    <volume-number>4</volume-number>
    <restriction>1</restriction>
  </info>
  <pvd>
    <volume-id>VIDEOCD</volume-id>
    <system-id>CD-RTOS CD-BRIDGE</system-id>
    <application-id>VIDEOCD.APP;1</application-id>
    <preparer-id>PREP_ID</preparer-id>
    <publisher-id>PUBL_ID</publisher-id>
  </pvd>

  <segment-items>
    <segment-item src="item0000.m1p" id="segment-0000"/>
    <segment-item src="item0000.m1p" id="segment-0001"/>
    <segment-item src="item0000.m1p" id="segment-0002"/>
  </segment-items>

  <sequence-items>
    <sequence-item src="avseq00.m1p" id="sequence-00">
      <default-entry id="entry-001"/>
    </sequence-item>
    <sequence-item src="avseq00.m1p" id="sequence-01"/>
    <sequence-item src="avseq00.m1p" id="sequence-02"/>
    <sequence-item src="avseq00.m1p" id="sequence-03">
      <entry id="entry-002">0.000000</entry>
    </sequence-item>
  </sequence-items>

  <pbc>
    <selection id="menu">
      <bsn>1</bsn>
      <next ref="lid-end"/>
      <return ref="lid-end" x1="10" y1="20" x2="30" y2="40"/>
      <wait>-1</wait>
      <loop jump-timing="immediate">1</loop>
      <play-item ref="segment-0000"/>
      <select ref="lid-000" />
      <select ref="lid-001" />
      <select ref="lid-end" />
    </selection>

    <playlist id="lid-000">
      <next ref="lid-001"/>
      <return ref="lid-end"/>
      <wait>5</wait>
      <autowait>0</autowait>
      <play-item ref="sequence-00"/>
      <play-item ref="sequence-01"/>
      <play-item ref="segment-0001"/>
      <play-item ref="entry-001"/>
    </playlist>

    <playlist id="lid-001">
      <next ref="lid-end"/>
      <return ref="lid-end"/>
      <wait>5</wait>
      <autowait>0</autowait>
      <play-item ref="sequence-02"/>
      <play-item ref="sequence-03"/>
      <play-item ref="segment-0002"/>
      <play-item ref="entry-002"/>
    </playlist>

    <endlist id="lid-end" rejected="true"/>
  </pbc>
</videocd>
